# Generated by Django 5.2.4 on 2025-07-25 14:13

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('xp_cost', models.PositiveIntegerField(help_text='The price of the item in XP.')),
                ('image', models.FileField(blank=True, null=True, upload_to=store.models.store_image_upload_path)),
                ('stock_quantity', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to hide the item from the student store view.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Item',
                'verbose_name_plural': 'Store Items',
                'ordering': ['xp_cost', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_cost_at_purchase', models.PositiveIntegerField(help_text='The XP cost of the item at the time of the transaction.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
