# Generated by Django 5.2.4 on 2025-07-26 07:34

import dev_xp_camp.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=dev_xp_camp.utils.get_upload_path),
        ),
    ]
