# Generated by Django 5.2.4 on 2025-07-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_storeitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='school',
        ),
    ]
