# Generated by Django 5.1 on 2025-07-21 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_xp', models.PositiveIntegerField(default=0, help_text='Lifetime XP earned for the leaderboard. This value does not decrease.')),
                ('available_xp', models.PositiveIntegerField(default=0, help_text='XP currently available for spending in the Dev Store.')),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
            },
        ),
    ]
