# Generated by Django 5.2.6 on 2025-09-13 17:02

import dev_xp_camp.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='report_card',
            field=models.FileField(blank=True, help_text="Student's report card image file", null=True, upload_to=dev_xp_camp.utils.get_upload_path),
        ),
    ]
