# users/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import UserViewSet, ChangePasswordView

# A router is used for ViewSets, which automatically generate URLs for list, create, retrieve, update, etc.
router = DefaultRouter()
router.register('', UserViewSet, basename='user') # Registers endpoints like /users/, /users/{id}/, /users/me/

urlpatterns = [
    # This path is for the user to change their own password.
    path('auth/change-password/', ChangePasswordView.as_view(), name='change-password'),
    
    # Include all the URLs generated by the router for the UserViewSet.
    # This should be last to ensure more specific paths are matched first.
    path('', include(router.urls)),
]